### ISSUE TITLE
Can't create dashboards nor App's

### ISSUE THREAD

**Issue by ricard0g0mes** [inverse/hassio-addon-emoncms#21]
![image](https://user-images.githubusercontent.com/10976309/114742018-399ea500-9d43-11eb-8746-dc8d6e577a03.png)
![image](https://user-images.githubusercontent.com/10976309/114742050-41f6e000-9d43-11eb-82a6-1bbb435e43d6.png)
![image](https://user-images.githubusercontent.com/10976309/114742133-5509b000-9d43-11eb-88bd-ab1af05dc1f3.png)

When trying to create an App or Dashboard, in dashboard nothing is done with the button.
Trying to add an App, i get this error.

**Comment by ricard0g0mes** [comment]
Solved updating database o think.
Will test it today

**Comment by inverse** [comment]
Let me know if there are any other issues - and how you fixed it. 

What do you mean updating the database? Def something to do with managing DB migrations we need to sort out in this addon.

**Comment by ricard0g0mes** [comment]
In the admin Page there is an option to update the database.
Solved my problems with creating dashboards

**Comment by inverse** [comment]
Oh nice - perhaps there is a way to call this automatically on version upgrades.

**Comment by ricard0g0mes** [comment]
Talk with me by whatsup if you want. I can create a user in my server and you can use it to try everything

**Comment by inverse** [comment]
@ricard0g0mes closing this one as `0.3.0` runs migrations on up
