### ISSUE TITLE
fseek() errors in log

### ISSUE THREAD

**Issue by alexdelprete** [inverse/hassio-addon-emoncms#32]
In Admin-> Sys. Info, in the log section on the bottom, an fseek() error is logged. Also, if you click on full update on the top, an error comes up.

![image](https://user-images.githubusercontent.com/7027842/122693379-e57bd980-d239-11eb-9eb6-7647928bdf42.png)

**Comment by inverse** [comment]
Hi @alexdelprete thanks for raising all these tickets. Not an emoncms user but will try and address them when I have time.

I fixed the log issue - https://github.com/inverse/hassio-addon-emoncms/pull/35

However the update one I am not sure how to progress since ideally you should not be doing application updates within the container as the application should be immutable. e.g. the versions are defined within the Dockerfile build process. 

What is your opinion on this?

**Comment by alexdelprete** [comment]
Hi Malachi,

I'm sorry if I opened too many in one shot, but I preferred to do it while I was starting studying how emoncms worked.

I think it will be difficult to fix things if you're not a user of the app, but you look like a skilled guy, so let's try. :)

> However the update one I am not sure how to progress since ideally you should not be doing application updates within the container as the application should be immutable. e.g. the versions are defined within the Dockerfile build process.

I thought about that, and I agree with what you say, but technically it's doable, right? We should check how the "official" docker version of emoncms works. If that has the updates disabled, I guess you should do the same. The only problem I see is that if you are not a user of the app, you will not be motivated to update it as often as the app is. 

But I really liked the idea of an HA addon version of the app, it makes a lot of sense. I hope you'll become a user of it. :)

**Comment by inverse** [comment]
Hi @alexdelprete,

I'm happy to help drive the project forward when I have some free time, but totally open to having external help if someone wants to help jump on ;)

I tested the official docker setup and it has the same situation.

![image](https://user-images.githubusercontent.com/713525/122993949-33aeeb00-d3a8-11eb-806f-327d79108b0b.png)

I'll merge the log one so at least that's unblocked.

No worries with the bulk of issues - it helps!

**Comment by alexdelprete** [comment]
Thanks. So I guess no updates within the docker version...like the official docker version. Makes sense.

**Comment by inverse** [comment]
@alexdelprete https://github.com/emoncms/emoncms/issues/1700

Lets see what they think 👍🏼
