### ISSUE TITLE
Feed Graph error

### ISSUE THREAD

**Issue by alexdelprete** [inverse/hassio-addon-emoncms#33]
From the feeds list, if you select the "Graph View" (the eye icon), an error comes up and no graph is shown.

![image](https://user-images.githubusercontent.com/7027842/122699734-3abfe700-d24a-11eb-991b-db05e3b32522.png)
![image](https://user-images.githubusercontent.com/7027842/122699740-401d3180-d24a-11eb-8a64-40d6f0f5c75e.png)

**Comment by inverse** [comment]
@alexdelprete is this one resolved with the change too?

**Comment by alexdelprete** [comment]
Yes it's resolved.
