### ISSUE TITLE
Many functions missing from the GUI

### ISSUE THREAD

**Issue by alexdelprete** [inverse/hassio-addon-emoncms#34]
If I look at the documentation, with screenshots of the GUI:

![image](https://user-images.githubusercontent.com/7027842/122703360-abb6cd00-d251-11eb-96ab-ae4a154762af.png)

And I compare it to what I see when I login to the integration version, you'll notice it's missing lot of things. I thought it had something to do with https, so I enabled it and refreshed, but it didn't change anything. I think there's some issue preventing those functions to show up in the GUI.

![image](https://user-images.githubusercontent.com/7027842/122703452-e7519700-d251-11eb-9130-4154f0e35fa6.png)

**Comment by inverse** [comment]
This and #33 looks like a bug with bumping the version of emoncms due to the menu change
 
When changing all the extensions to use master it seems to work 

![image](https://user-images.githubusercontent.com/713525/122999718-eaae6500-d3ae-11eb-9845-0f77dbebc554.png)

**Comment by inverse** [comment]
@alexdelprete looks like they will need to tag new versions for this to work properly with the new menu system. I rolled back from `10.5.5` to bring it back to a working state which should fix most your issues, aside the Redis one.

See: https://github.com/inverse/hassio-addon-emoncms/releases/tag/0.4.1

Lemmi know if it worked

**Comment by alexdelprete** [comment]
> Lemmi know if it worked

It worked. Finally I can start using it. :)

Thanks so much.

**Comment by roy13** [comment]
EMONHUB is something i think many of us could benafit from. This is essential for a lot of existing systems to migate to this addon.
I myself have serial data coming in via EMONHUB so can't start playing untill that is accessible.
